## Create and Use Functions & Modules

If we want to employ Python for a specific use case we usually import Modules or Functions that do the job for us.
But what happens in the case that there is no function or module that helps us with our problem.
Right we create our own. In this Block I will show you how to write functions and use modules in Python.

If we want to know which Functions or Modules are currently available use the dir() function.

In [2]:
dir()

['In',
 'Out',
 '_',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'exit',
 'get_ipython',
 'quit']

Now we can create our first function named after the famous Pokemon Magikarp and just like Magikarp it does not too much..

In [3]:
def magikarp():
    pass

Use the next cell to call dir() again and see if the function now appears. 
Also you can try running the function by typing magikarp()

We can also assign a return statement to a function to recieve an output. However this is not necessary.

In [4]:
def magikarp():
    return 'Magikarp used splash! But nothing happened!'

Try calling the function again to see if the output changed

In [5]:
magikarp()

'Magikarp used splash! But nothing happened!'

### Function Challenge

Remember the For-Loop Challenge? Wrap the loop into a function with 1 input argument. 
This argument should determine the total amount of iterations for the loop.

Now lets do something more serious. Lets create a function that estimates the area of a circle

To do that first import the math package to get the function pi

In [6]:
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

Now lets create a function that calculates the area of a circle for you. It is common practice to specify a docstring in the beginning of the function in order to explain what the function does. When you call help(area_circle) after defining it you will see the information specified in the docstring.

In [7]:
def area_circle(r):
    
    '''This function returns the area of a circle based on the Radius (r)'''
    
    A=r**2*math.pi
    
    return 'The area of the circle is %f' % A

Now try to call our function to calculate the area of a circle with radius 3. Also 
check what happens when you give no input and try to call the help function on area_circle.

In [8]:
help(area_circle)

Help on function area_circle in module __main__:

area_circle(r)
    This function returns the area of a circle based on the Radius (r)



Functions can take more than only one input argument. In the next cell try to create a function that gives you the area of a triangle. The area of a triangle is calculated as: 
        
        Area = 0.5 * Base * Height
        
If you have a solution you can compare it to mine by removing the X of the cell underneath and running the cell

In general Functions can be used with two different kinds of input parameters. So far we only used parameters that had to be defined, but there are also so-called default parameters. If we call a function with a default parameter without specifying a parameter the default parameter will be used.

In [10]:
def my_name(name='slim shady'):
    
    '''This function prints the name of the godfather of rap (if not specified otherwise)'''
    
    print('My name is %s' % name)

In [11]:
my_name()

My name is slim shady


## Lambdas (anonymous functions)

Sometimes you just want to do a very simple operation, so you are unsure whether its worth defining a function for it. But you kinda need to do the operation multiple times and you don't want to repeat your code. In that case lambdas are your friend. Lambdas are anonymous functions they are called anonymous, because they are defined without a name. Although they can be bound to a name. A lambda function can take any number of arguments, but can only have one expression.

    lambda arguments : expression
    
Or (and this is probably the more reasonable case for a lambda) You want to define a function that can return a function.

In [34]:
num2string = lambda x : str(x) + ' your number is now in a string'

print(num2string(8))

#Create a function that can return a function using a lambda expression
def my_multiplier(n):
    return lambda a : a * n

mydoubler = my_multiplier(2)
mytripler = my_multiplier(3)

8 your number is now in a string


In [30]:
print(mydoubler(10))
print(mytripler(10))

20
30


## Modules

Sometimes creating a single function is not enough and it can be quite tedious to call each function separately.
In order to avoid this annoying problem functions can be put in modules. So instead of calling each function seperately you can simply import a module like "math" to get immediate access to many different functions. in the Next part of this tutorial we will have look at a super useful Module called numpy.


## How to work with matrices
   Our goal is to analyse MEG data (probably not true for everyone :D )
   This kind of data is commonly represented as a matrix. A matrix has a certain number of rows and columns. Each cell
   contains one number which in the case of MEG data is the current magnetic
   field in either Tesla (for magnetometers) or Tesla/meter for gradiometers.
   Each row of the matrix is one channel and each column is one sample.
   Treating the data as a matrix has one more advantage (besides being quite
   intuitive): Calculations on matrices are quite fast on computers because
   algorithms and even the CPUs themselves are optimized to operate on matrices.

   Unfortunately, working with matrices is NOT part of Python itself. However,
   Python can be extended using so-called "packages/modules".
   In order to use packages/modules, we need to

   1. Install them. In your case, this is irrelevant as the script you are running here is basically on my laptop.
      But if you want to do some proper analysis at home you need to install the packages using conda or pip
   2. Import the packages you actually need in your script. This is done
      with the import statement.

The package we need for matrix operation is called numpy. There is a
convention to "rename" it in scripts, this is what the "as np" part is for:

In [13]:
import numpy as np

Now we can use all the functions of numpy in our script. You can take a look at the official documentation here: https://docs.scipy.org/doc/numpy/reference/ to see what you can do with it. I will just give a few examples here.

The first thing we need to do is make a matrix:

In [14]:
my_matrix = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9],
                      [10, 11, 12]])

What happens here is that we create a list that contains a list for each row
of the matrix we want to create. We then call np.array with that list and
get a matrix with four rows and three columns in return.
If we want to know how big our matrix is, we can ask for its shape property:

In [15]:
my_matrix.shape

(4, 3)

You can access the elements of the matrix using the [ ] notation you already
know from lists and dictionaries:

In [16]:
print(my_matrix[0]) # The first row
print(my_matrix[0, 0]) # The element in the first row and first column
print(my_matrix[1, 2]) # Second row, third column
print(my_matrix[0:3, 2]) # Thirs column, the first three elements
print(my_matrix[:, 1]) # All elements of the second column

[1 2 3]
1
6
[3 6 9]
[ 2  5  8 11]


There are also some methods that can be applied to matrices:

In [17]:
print(my_matrix.mean()) # The mean of all elements
print(my_matrix.mean(axis=0)) # Mean over all rows
print(my_matrix.mean(axis=1)) # Mean over columns

print(my_matrix.sum())
print(my_matrix.sum(axis=0))
print(my_matrix.sum(axis=1))

6.5
[5.5 6.5 7.5]
[ 2.  5.  8. 11.]
78
[22 26 30]
[ 6 15 24 33]


We can also do math with matrices

In [18]:
new_matrix = my_matrix + 2 # Create a new matrix with all the elements of the old one +2
print(new_matrix)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## The difference between assignments and copys
In most cases, python variables do NOT contain the actual values but just
the address of the element in the RAM of the computer. This is the case
for all variables that are more complex than holding a single value or a
single string.
I.e. it is the case for:
   * lists
   * dictionaries
   * matrices
   * any Python object we are going to use in the next script.

Here is an example

In [19]:
first_list = [1, 2, 3, 4]
second_list = first_list
second_list[2] = 999

print(first_list)

[1, 2, 999, 4]


You can see that although we modified second_list, we see the change
even when we look at first_list.
The reason is that when we did this:
    
    second_list = first_list
    
We only said: "second_list shall point to the same list as first_list"

If you want a real copy of an object (i.e. list, dictionary, matrix),
you can either see whether that object has a copy method like the matrices:

In [20]:
copied_matrix = my_matrix.copy()

Or if they do not, you can use the copy package of python, which you need
to import first:

In [21]:
import copy

third_list = copy.copy(first_list)
third_list[2] = 666

print(first_list)
print(third_list)

[1, 2, 999, 4]
[1, 2, 666, 4]


## Context Managers -- Efficiently handling resources in Python

If you work with files using a context manager might be a good idea. 
Context managers handle the tear down of the resources automatically -> So no need to close files. This can be quite useful. As it saves resources. here are two different ways of writing somethin to a file.


In [24]:
#open, write and close a file
f = open('sample.txt', 'w')
f.write('This is super boring..')
f.close()

#do the same using a context manager
with open('sample2.txt', 'w') as f:
    f.write('This is still super boring')

This is not only useful for files, but also for working with databases etc. In Python you can even define your own context manager if you want to. However, for now we will just hijack pythons 'with' statement. Using the with statement is something thats important if using pymc ;). Everything that happens in the scope of with is happening "with"-in that context. If you want to do something with the file you need to either open it again and close it separately or use the with statement again

In [28]:
with open('sample2.txt', 'r') as f:
    print(f.read())

This is still super boring
